insert into Items (Item_Name, Item_Stock, Item_Price) values ('Mackerel Whole Fresh', 3, 10203);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Mace', 27, 5694);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Ox Tail, Frozen', 25, 9041);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Chateauneuf Du Pape', 12, 7349);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Tortillas - Flour, 12', 50, 12867);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Capers - Pickled', 55, 10040);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Foil Cont Round', 19, 12843);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Bread - Petit Baguette', 26, 14014);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Devonshire Cream', 23, 5305);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Striploin Aa', 86, 6675);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef Wellington', 28, 14820);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Grapes - Black', 6, 9800);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Red, Pinot Noir, Chateau', 2, 12423);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Ice Cream - Vanilla', 87, 12883);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beer - Heinekin', 35, 7750);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wonton Wrappers', 6, 6693);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cleaner - Comet', 75, 12908);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Red Pepper Paste', 44, 14573);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Potatoes - Mini White 3 Oz', 100, 14361);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Apples - Sliced / Wedge', 10, 8304);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Flower - Leather Leaf Fern', 101, 10137);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Glass Clear 7 Oz Xl', 101, 14777);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Soup - Campbells, Lentil', 21, 13716);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Syrup - Monin, Amaretta', 75, 11312);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Rappini - Andy Boy', 5, 6276);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Pork - Inside', 50, 13030);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Pepper - Black, Crushed', 83, 13315);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Campari', 53, 6904);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Potatoes - Mini Red', 83, 13484);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Kiwi Gold Zespri', 101, 8210);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - Goat With Herbs', 75, 7803);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Lid - 16 Oz And 32 Oz', 99, 10699);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Montecillo Rioja Crianza', 25, 9261);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Magnotta - Belpaese', 24, 6648);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Soup Bowl Clear 8oz92008', 94, 6451);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Bread Crumbs - Panko', 79, 11787);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - Cheddar, Medium', 91, 12343);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Salmon Steak - Cohoe 6 Oz', 66, 10273);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Two Oceans Sauvignon', 87, 14826);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Alize Red Passion', 78, 12475);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Lamb - Shanks', 36, 8084);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Sauce - Mint', 82, 14318);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cloves - Ground', 41, 14730);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Tamarillo', 54, 7592);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Bourgogne 2002, La', 7, 10800);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Ecolab Crystal Fusion', 39, 9265);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chicken - White Meat, No Tender', 28, 6241);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Lettuce - Red Leaf', 9, 6111);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Peller Estates Late', 34, 6050);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Split Peas - Yellow, Dry', 5, 13925);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('White Fish - Filets', 31, 14359);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Top Sirloin - Aaa', 57, 7302);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chevere Logs', 82, 7504);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Top Sirloin', 49, 14765);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Bread - Rye', 75, 9251);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Prosecco Valdobiaddene', 75, 9196);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Fat Bastard Merlot', 16, 13051);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Carbonated Water - White Grape', 51, 12123);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Rice - Wild', 77, 5582);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Jameson - Irish Whiskey', 63, 8236);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Ham - Proscuitto', 40, 11609);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Calypso - Strawberry Lemonade', 77, 8941);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chicken Thigh - Bone Out', 85, 14238);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Hold Up Tool Storage Rack', 101, 9584);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - Mozzarella', 34, 9665);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Outside, Round', 10, 12397);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Muffin Mix - Oatmeal', 68, 5825);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Food Colouring - Green', 1, 9949);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Herb Du Provence - Primerba', 52, 13595);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Longan', 6, 9937);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Ice Wine', 46, 11262);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chicken Breast Halal', 41, 13250);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Piping - Bags Quizna', 61, 10029);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Initation Crab Meat', 7, 6946);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chinese Lemon Pork', 100, 5459);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Rib Roast, Capless', 71, 13942);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cucumber - Pickling Ontario', 96, 13428);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Wine - Redchard Merritt', 68, 14683);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Chocolate - Compound Coating', 4, 11977);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Bread Base - Toscano', 30, 13466);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - Havarti, Salsa', 85, 5939);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - St. Andre', 71, 7929);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Leeks - Baby, White', 70, 6172);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Sugar - Fine', 55, 11300);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Water - Mineral, Carbonated', 25, 11385);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Pork - Belly Fresh', 35, 8881);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Mousse - Mango', 66, 9169);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Vodka - Smirnoff', 23, 8878);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Tea - Lemon Scented', 43, 13387);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Cheese - Wine', 62, 13829);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Pork - Butt, Boneless', 84, 10339);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Oil - Truffle, Black', 19, 8108);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Pineapple - Canned, Rings', 3, 8430);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Clams - Littleneck, Whole', 31, 8331);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Tortillas - Flour, 12', 56, 10267);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Tea - Herbal Sweet Dreams', 57, 9896);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Orange - Tangerine', 10, 7439);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Onions - Red', 73, 14496);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Beef - Striploin', 64, 9389);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Flower - Leather Leaf Fern', 48, 5692);
insert into Items (Item_Name, Item_Stock, Item_Price) values ('Lobster - Tail, 3 - 4 Oz', 89, 11912);
